name: Build and Release
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Executable Setup
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v1.4.${{ github.run_number }}"
          name: "Nuevo Lanzamiento Nexus v1.4.${{ github.run_number }}"
          files: ../dist/*.exe
          body: "Ultima version autogenerada. Descargar Setup para instalar."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
